name: Syncope CI Build and Analyze - Data Flow Coverage
run-name: ${{ github.actor }} is building and analyzing Syncope - Data Flow Coverage
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64
          cache: maven

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify -P df-coverage

      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: badua.xml
          path: core/spring/target/badua.xml
          if-no-files-found: error
