name: Syncope CI Demo
run-name: ${{ github.actor }} is testing out GitHub Actions on Syncope 🚀
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: x64
          cache: maven
      - name: Verify with Maven
        run: mvn -B verify
